export {
	DKGClient,
	type DKGClientConfig,
	generatePolynomial,
	evaluatePolynomial,
	computeCommitments,
	verifyShareAgainstCommitments,
	combinePublicKeys,
	computeLagrangeCoefficient,
	aggregateShares,
	scalarToHex,
	hexToScalar,
	CURVE_ORDER,
	createPedersenCommitment,
	verifyPedersenCommitment,
	createVSSSCommitments,
	verifyVSSSCommitment,
	verifyProofOfKnowledge,
	combineVSSSCommitments,
	encryptShare,
	decryptShare,
	generateEphemeralKeyPair,
	serializeEncryptedShare,
	deserializeEncryptedShare,
	type PedersenCommitment,
	type VSSSCommitment,
	type EncryptedShare,
	type DecryptedShare,
} from "./dkg";

export {
	SigningClient,
	createSigningClient,
	type SigningClientConfig,
	generateNonceShare,
	createNonceCommitment,
	verifyNonceCommitment,
	combineNonceCommitments,
	computeR,
	computePartialSignature,
	combinePartialSignatures,
	formatSignature,
	parseMessageHash,
	verifyPartialSignature,
	type NonceShare,
	type NonceCommitment,
	type NonceDecommitment,
	type PartialSignatureData,
} from "./signing";

export {
	DKLSClient,
	createDKLSClient,
	type DKLSClientConfig,
	keygenInitClient,
	keygenProcessBackendCommitment,
	keygenGenerateReveal,
	keygenComplete,
	signingInit,
	signingProcessBackendNonce,
	generateSchnorrProof,
	deriveEthereumAddress,
	serializeKeyShare,
	type DKLSKeygenClientState,
	type DKLSSigningClientState,
	type DKLSKeyShare,
	type DKLSSchnorrProof,
	type DKLSKeygenCommitment,
	type DKLSKeygenPublicShare,
	type DKLSNonceCommitment,
	type DKLSSigningResult,
	type DKLSKeygenSessionState,
	type DKLSSigningSessionState,
	type DKLSSignRequest,
} from "./dkls";
